import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Forward Science Automation | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center "></main>
    </>
  );
};

export default Home;
